name: Generate all articles
on:
  - push

jobs:
  generate:
    name: articles-generate-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
          cache: false
      - name: Install microblogen
        run: GOBIN=$(pwd) GOPRIVATE="github.com/Qman11010101/microblogen" go install github.com/Qman11010101/microblogen@latest
      - run: ls -la
      - name: run microblogen
        run: $(pwd)/microblogen
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=github-actions[bot] -m 'generated'
          git push