name: Generate all articles when article is updated
on:
  repository_dispatch:
    types: [update_post]

jobs:
  generate:
    name: articles-generate-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.3"
          cache: false
      - name: Event display
        run: |
          echo ${{github.event.client_payload.type}}
          echo ${{github.event.client_payload.id}}
      - name: Install microblogen
        run: GOBIN=$(pwd) GOPRIVATE="github.com/Qman11010101/microblogen" go install github.com/Qman11010101/microblogen@latest
      - name: run microblogen
        run: $(pwd)/microblogen
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
          TZ: "Asia/Tokyo"
      - name: remove microblogen binary
        run: rm microblogen
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'Automatically generated'
          git push
      - name: Python environment
        if: github.event.client_payload.type == 'new' || github.event.client_payload.type == 'edit'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Tweet
        if: github.event.client_payload.type == 'new' || github.event.client_payload.type == 'edit'
        run: |
          pip install requests_oauthlib
          python .github/workflows/tweet.py
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          ID: ${{github.event.client_payload.id}}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
          TIMEZONE: "Asia/Tokyo"
