name: Generate all articles when template is renewed
on:
  push:
    branches:
      - main

jobs:
  generate:
    name: articles-generate-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.23.0'
          cache: false
      - name: Install microblogen
        run: GOBIN=$(pwd) GOPRIVATE="github.com/Qman11010101/microblogen" go install github.com/Qman11010101/microblogen@latest
      - name: run microblogen
        run: $(pwd)/microblogen
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
          TIMEZONE: "Asia/Tokyo"
      - name: remove microblogen binary
        run: rm microblogen
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch origin pages-prod || git branch pages-prod
          git checkout -B pages-prod origin/pages-prod || git checkout -B pages-prod
          git rm -rf .
          cp -r output/* .
          rm -rf output
          git add .
          git commit -m "Deploy: $(date -u)"
          git push origin pages-prod --force
