name: Generate all articles when something pushed to preview
on:
  push:
    branches:
      - preview

jobs:
  generate:
    name: articles-generate-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
      - name: Change branch and reset
        run: |
          set -x
          git fetch origin pages-prev || git branch pages-prev
          git checkout -B pages-prev origin/pages-prev || git checkout -B pages-prev
          git reset --hard origin/preview
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
          cache: false
      - name: Install microblogen
        run: GOBIN=$(pwd) GOPRIVATE="github.com/Qman11010101/microblogen" go install github.com/Qman11010101/microblogen/v2@latest
      - name: run microblogen
        run: $(pwd)/microblogen
        env:
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          SERVICE_DOMAIN: ${{ secrets.SERVICE_DOMAIN }}
          EXPORT_PATH: "./output"
          RESOURCES_PATH: "./resources"
          LATEST_ARTICLES: 5
          ARTICLES_PER_PAGE: 10
          TIMEZONE: "Asia/Tokyo"
          CATEGORY_TAG_NAME: "Category"
          TIME_ARCHIVE_NAME: "Archive"
      - name: remove microblogen binary & .github
        run: |
          rm microblogen
          rm -rf .github
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Deploy: $(date -u)"
          git push origin pages-prev --force
